spring:
  application:
    name: spring-store
  flyway:
    locations: classpath:src/main/resources/db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/ab_sql?createDatabaseIfNotExist=true
    username: root
    password: MySQL4908diesel
  jpa:
    show-sql: true

kind: Application